name: "SAPUI5 End Of Cloud Provisioning version check"
description: "Checks the current version inside your project of SAPUI5 and it wil warn you when it is EOCP"
inputs:
  owner:
    description: "The owner of the repository"
    required: true
  repo:
    description: "The name of the repository"
    required: true
  issueNumber:
    description: "The number of the pull request"
    required: true
  token:
    description: "The token to use to access the GitHub API"
    required: true
  pathToIndex:
    description: "Path to index.html where the version is specified"
    required: true
  failOnEOCP:
    description: "Make action fail if EOCP is in current Q"
    type: boolean
    required: true
runs:
  using: "node16"
  main: "index.js"
